# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    routing_loader:
        include_format: false
    view:
        view_response_listener: true
    format_listener:
        enabled: true
        rules:
            - { path: '^/api/', priorities: ['json'], fallback_format: 'json', prefer_extension: false }
    exception:
        enabled: true
        exception_controller: 'fos_rest.exception.controller:showAction'
    body_listener:
        enabled: true
    serializer:
        serialize_null: true

