jms_serializer:
    metadata:
        directories:
            configuration-database:
                namespace_prefix: "App\\Entity"
                path: "%kernel.root_dir%/Resources/config/serializer"
