App\Entity\FlashSale:
  properties:
    id:
      groups: ['service']
    name:
      groups: ['service']
    description:
      groups: ['service']
    image:
      groups: ['service']
    beginDate:
      groups: ['service']
    endDate:
      groups: ['service']
    price:
      groups: ['service']
    products:
      groups: ['service']
