App\Entity\Product:
  properties:
    id:
      groups: ['service']
    name:
      groups: ['service']
    description:
      groups: ['service']
    image:
      groups: ['service']
    status:
      groups: ['service']
    price:
      groups: ['service']
    discountEndDate:
      groups: ['service']  
    discountBeginDate:
      groups: ['service']
    createdAt:
      groups: ['service']
    discount:
      groups: ['service']
    seller:
      groups: ['service']
    category:
      groups: ['service']
